// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/MonitorService.proto

package rpcapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Average system load
type AvgSysLoad struct {
	One                  float64  `protobuf:"fixed64,1,opt,name=one,proto3" json:"one,omitempty"`
	Five                 float64  `protobuf:"fixed64,2,opt,name=five,proto3" json:"five,omitempty"`
	Quater               float64  `protobuf:"fixed64,3,opt,name=quater,proto3" json:"quater,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvgSysLoad) Reset()         { *m = AvgSysLoad{} }
func (m *AvgSysLoad) String() string { return proto.CompactTextString(m) }
func (*AvgSysLoad) ProtoMessage()    {}
func (*AvgSysLoad) Descriptor() ([]byte, []int) {
	return fileDescriptor_2301b6814c8530ba, []int{0}
}

func (m *AvgSysLoad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvgSysLoad.Unmarshal(m, b)
}
func (m *AvgSysLoad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvgSysLoad.Marshal(b, m, deterministic)
}
func (m *AvgSysLoad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvgSysLoad.Merge(m, src)
}
func (m *AvgSysLoad) XXX_Size() int {
	return xxx_messageInfo_AvgSysLoad.Size(m)
}
func (m *AvgSysLoad) XXX_DiscardUnknown() {
	xxx_messageInfo_AvgSysLoad.DiscardUnknown(m)
}

var xxx_messageInfo_AvgSysLoad proto.InternalMessageInfo

func (m *AvgSysLoad) GetOne() float64 {
	if m != nil {
		return m.One
	}
	return 0
}

func (m *AvgSysLoad) GetFive() float64 {
	if m != nil {
		return m.Five
	}
	return 0
}

func (m *AvgSysLoad) GetQuater() float64 {
	if m != nil {
		return m.Quater
	}
	return 0
}

// Average cpu load
type AvgCpuLoad struct {
	Usr                  float64  `protobuf:"fixed64,1,opt,name=usr,proto3" json:"usr,omitempty"`
	Sys                  float64  `protobuf:"fixed64,2,opt,name=sys,proto3" json:"sys,omitempty"`
	Idle                 float64  `protobuf:"fixed64,3,opt,name=idle,proto3" json:"idle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvgCpuLoad) Reset()         { *m = AvgCpuLoad{} }
func (m *AvgCpuLoad) String() string { return proto.CompactTextString(m) }
func (*AvgCpuLoad) ProtoMessage()    {}
func (*AvgCpuLoad) Descriptor() ([]byte, []int) {
	return fileDescriptor_2301b6814c8530ba, []int{1}
}

func (m *AvgCpuLoad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvgCpuLoad.Unmarshal(m, b)
}
func (m *AvgCpuLoad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvgCpuLoad.Marshal(b, m, deterministic)
}
func (m *AvgCpuLoad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvgCpuLoad.Merge(m, src)
}
func (m *AvgCpuLoad) XXX_Size() int {
	return xxx_messageInfo_AvgCpuLoad.Size(m)
}
func (m *AvgCpuLoad) XXX_DiscardUnknown() {
	xxx_messageInfo_AvgCpuLoad.DiscardUnknown(m)
}

var xxx_messageInfo_AvgCpuLoad proto.InternalMessageInfo

func (m *AvgCpuLoad) GetUsr() float64 {
	if m != nil {
		return m.Usr
	}
	return 0
}

func (m *AvgCpuLoad) GetSys() float64 {
	if m != nil {
		return m.Sys
	}
	return 0
}

func (m *AvgCpuLoad) GetIdle() float64 {
	if m != nil {
		return m.Idle
	}
	return 0
}

// Disks information
type DiskInfo struct {
	Tps                  float64  `protobuf:"fixed64,1,opt,name=tps,proto3" json:"tps,omitempty"`
	Kbrps                float64  `protobuf:"fixed64,2,opt,name=kbrps,proto3" json:"kbrps,omitempty"`
	Kbwps                float64  `protobuf:"fixed64,3,opt,name=kbwps,proto3" json:"kbwps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskInfo) Reset()         { *m = DiskInfo{} }
func (m *DiskInfo) String() string { return proto.CompactTextString(m) }
func (*DiskInfo) ProtoMessage()    {}
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2301b6814c8530ba, []int{2}
}

func (m *DiskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskInfo.Unmarshal(m, b)
}
func (m *DiskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskInfo.Marshal(b, m, deterministic)
}
func (m *DiskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskInfo.Merge(m, src)
}
func (m *DiskInfo) XXX_Size() int {
	return xxx_messageInfo_DiskInfo.Size(m)
}
func (m *DiskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DiskInfo proto.InternalMessageInfo

func (m *DiskInfo) GetTps() float64 {
	if m != nil {
		return m.Tps
	}
	return 0
}

func (m *DiskInfo) GetKbrps() float64 {
	if m != nil {
		return m.Kbrps
	}
	return 0
}

func (m *DiskInfo) GetKbwps() float64 {
	if m != nil {
		return m.Kbwps
	}
	return 0
}

type DiskStats struct {
	Stats                map[string]*DiskInfo `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DiskStats) Reset()         { *m = DiskStats{} }
func (m *DiskStats) String() string { return proto.CompactTextString(m) }
func (*DiskStats) ProtoMessage()    {}
func (*DiskStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_2301b6814c8530ba, []int{3}
}

func (m *DiskStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskStats.Unmarshal(m, b)
}
func (m *DiskStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskStats.Marshal(b, m, deterministic)
}
func (m *DiskStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskStats.Merge(m, src)
}
func (m *DiskStats) XXX_Size() int {
	return xxx_messageInfo_DiskStats.Size(m)
}
func (m *DiskStats) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskStats.DiscardUnknown(m)
}

var xxx_messageInfo_DiskStats proto.InternalMessageInfo

func (m *DiskStats) GetStats() map[string]*DiskInfo {
	if m != nil {
		return m.Stats
	}
	return nil
}

type FSD struct {
	Source               string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Fs                   string   `protobuf:"bytes,2,opt,name=fs,proto3" json:"fs,omitempty"`
	Total                float64  `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
	Used                 float64  `protobuf:"fixed64,4,opt,name=used,proto3" json:"used,omitempty"`
	Percent              float64  `protobuf:"fixed64,5,opt,name=percent,proto3" json:"percent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FSD) Reset()         { *m = FSD{} }
func (m *FSD) String() string { return proto.CompactTextString(m) }
func (*FSD) ProtoMessage()    {}
func (*FSD) Descriptor() ([]byte, []int) {
	return fileDescriptor_2301b6814c8530ba, []int{4}
}

func (m *FSD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FSD.Unmarshal(m, b)
}
func (m *FSD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FSD.Marshal(b, m, deterministic)
}
func (m *FSD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FSD.Merge(m, src)
}
func (m *FSD) XXX_Size() int {
	return xxx_messageInfo_FSD.Size(m)
}
func (m *FSD) XXX_DiscardUnknown() {
	xxx_messageInfo_FSD.DiscardUnknown(m)
}

var xxx_messageInfo_FSD proto.InternalMessageInfo

func (m *FSD) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *FSD) GetFs() string {
	if m != nil {
		return m.Fs
	}
	return ""
}

func (m *FSD) GetTotal() float64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *FSD) GetUsed() float64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *FSD) GetPercent() float64 {
	if m != nil {
		return m.Percent
	}
	return 0
}

type FSDStats struct {
	Fsdblocks            []*FSD   `protobuf:"bytes,1,rep,name=fsdblocks,proto3" json:"fsdblocks,omitempty"`
	Fsdinodes            []*FSD   `protobuf:"bytes,2,rep,name=fsdinodes,proto3" json:"fsdinodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FSDStats) Reset()         { *m = FSDStats{} }
func (m *FSDStats) String() string { return proto.CompactTextString(m) }
func (*FSDStats) ProtoMessage()    {}
func (*FSDStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_2301b6814c8530ba, []int{5}
}

func (m *FSDStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FSDStats.Unmarshal(m, b)
}
func (m *FSDStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FSDStats.Marshal(b, m, deterministic)
}
func (m *FSDStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FSDStats.Merge(m, src)
}
func (m *FSDStats) XXX_Size() int {
	return xxx_messageInfo_FSDStats.Size(m)
}
func (m *FSDStats) XXX_DiscardUnknown() {
	xxx_messageInfo_FSDStats.DiscardUnknown(m)
}

var xxx_messageInfo_FSDStats proto.InternalMessageInfo

func (m *FSDStats) GetFsdblocks() []*FSD {
	if m != nil {
		return m.Fsdblocks
	}
	return nil
}

func (m *FSDStats) GetFsdinodes() []*FSD {
	if m != nil {
		return m.Fsdinodes
	}
	return nil
}

type TopTalkersStats struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopTalkersStats) Reset()         { *m = TopTalkersStats{} }
func (m *TopTalkersStats) String() string { return proto.CompactTextString(m) }
func (*TopTalkersStats) ProtoMessage()    {}
func (*TopTalkersStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_2301b6814c8530ba, []int{6}
}

func (m *TopTalkersStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopTalkersStats.Unmarshal(m, b)
}
func (m *TopTalkersStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopTalkersStats.Marshal(b, m, deterministic)
}
func (m *TopTalkersStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopTalkersStats.Merge(m, src)
}
func (m *TopTalkersStats) XXX_Size() int {
	return xxx_messageInfo_TopTalkersStats.Size(m)
}
func (m *TopTalkersStats) XXX_DiscardUnknown() {
	xxx_messageInfo_TopTalkersStats.DiscardUnknown(m)
}

var xxx_messageInfo_TopTalkersStats proto.InternalMessageInfo

type Listeners struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Protoc               string   `protobuf:"bytes,3,opt,name=protoc,proto3" json:"protoc,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listeners) Reset()         { *m = Listeners{} }
func (m *Listeners) String() string { return proto.CompactTextString(m) }
func (*Listeners) ProtoMessage()    {}
func (*Listeners) Descriptor() ([]byte, []int) {
	return fileDescriptor_2301b6814c8530ba, []int{7}
}

func (m *Listeners) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listeners.Unmarshal(m, b)
}
func (m *Listeners) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listeners.Marshal(b, m, deterministic)
}
func (m *Listeners) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listeners.Merge(m, src)
}
func (m *Listeners) XXX_Size() int {
	return xxx_messageInfo_Listeners.Size(m)
}
func (m *Listeners) XXX_DiscardUnknown() {
	xxx_messageInfo_Listeners.DiscardUnknown(m)
}

var xxx_messageInfo_Listeners proto.InternalMessageInfo

func (m *Listeners) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *Listeners) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Listeners) GetProtoc() string {
	if m != nil {
		return m.Protoc
	}
	return ""
}

func (m *Listeners) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type NetStats struct {
	TuListeners          []*Listeners       `protobuf:"bytes,1,rep,name=tu_listeners,json=tuListeners,proto3" json:"tu_listeners,omitempty"`
	States               map[string]float64 `protobuf:"bytes,2,rep,name=states,proto3" json:"states,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NetStats) Reset()         { *m = NetStats{} }
func (m *NetStats) String() string { return proto.CompactTextString(m) }
func (*NetStats) ProtoMessage()    {}
func (*NetStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_2301b6814c8530ba, []int{8}
}

func (m *NetStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetStats.Unmarshal(m, b)
}
func (m *NetStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetStats.Marshal(b, m, deterministic)
}
func (m *NetStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetStats.Merge(m, src)
}
func (m *NetStats) XXX_Size() int {
	return xxx_messageInfo_NetStats.Size(m)
}
func (m *NetStats) XXX_DiscardUnknown() {
	xxx_messageInfo_NetStats.DiscardUnknown(m)
}

var xxx_messageInfo_NetStats proto.InternalMessageInfo

func (m *NetStats) GetTuListeners() []*Listeners {
	if m != nil {
		return m.TuListeners
	}
	return nil
}

func (m *NetStats) GetStates() map[string]float64 {
	if m != nil {
		return m.States
	}
	return nil
}

type Statistic struct {
	SysLoad              *AvgSysLoad      `protobuf:"bytes,1,opt,name=sys_load,json=sysLoad,proto3" json:"sys_load,omitempty"`
	CpuLoad              *AvgCpuLoad      `protobuf:"bytes,2,opt,name=cpu_load,json=cpuLoad,proto3" json:"cpu_load,omitempty"`
	DiskInfo             *DiskStats       `protobuf:"bytes,3,opt,name=disk_info,json=diskInfo,proto3" json:"disk_info,omitempty"`
	FsInfo               *FSDStats        `protobuf:"bytes,4,opt,name=fs_info,json=fsInfo,proto3" json:"fs_info,omitempty"`
	Tts                  *TopTalkersStats `protobuf:"bytes,5,opt,name=tts,proto3" json:"tts,omitempty"`
	Net                  *NetStats        `protobuf:"bytes,6,opt,name=net,proto3" json:"net,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Statistic) Reset()         { *m = Statistic{} }
func (m *Statistic) String() string { return proto.CompactTextString(m) }
func (*Statistic) ProtoMessage()    {}
func (*Statistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_2301b6814c8530ba, []int{9}
}

func (m *Statistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statistic.Unmarshal(m, b)
}
func (m *Statistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statistic.Marshal(b, m, deterministic)
}
func (m *Statistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statistic.Merge(m, src)
}
func (m *Statistic) XXX_Size() int {
	return xxx_messageInfo_Statistic.Size(m)
}
func (m *Statistic) XXX_DiscardUnknown() {
	xxx_messageInfo_Statistic.DiscardUnknown(m)
}

var xxx_messageInfo_Statistic proto.InternalMessageInfo

func (m *Statistic) GetSysLoad() *AvgSysLoad {
	if m != nil {
		return m.SysLoad
	}
	return nil
}

func (m *Statistic) GetCpuLoad() *AvgCpuLoad {
	if m != nil {
		return m.CpuLoad
	}
	return nil
}

func (m *Statistic) GetDiskInfo() *DiskStats {
	if m != nil {
		return m.DiskInfo
	}
	return nil
}

func (m *Statistic) GetFsInfo() *FSDStats {
	if m != nil {
		return m.FsInfo
	}
	return nil
}

func (m *Statistic) GetTts() *TopTalkersStats {
	if m != nil {
		return m.Tts
	}
	return nil
}

func (m *Statistic) GetNet() *NetStats {
	if m != nil {
		return m.Net
	}
	return nil
}

type Request struct {
	Timeout              int32    `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	AverageInterval      int32    `protobuf:"varint,2,opt,name=average_interval,json=averageInterval,proto3" json:"average_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2301b6814c8530ba, []int{10}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Request) GetAverageInterval() int32 {
	if m != nil {
		return m.AverageInterval
	}
	return 0
}

func init() {
	proto.RegisterType((*AvgSysLoad)(nil), "monitor.AvgSysLoad")
	proto.RegisterType((*AvgCpuLoad)(nil), "monitor.AvgCpuLoad")
	proto.RegisterType((*DiskInfo)(nil), "monitor.DiskInfo")
	proto.RegisterType((*DiskStats)(nil), "monitor.DiskStats")
	proto.RegisterMapType((map[string]*DiskInfo)(nil), "monitor.DiskStats.StatsEntry")
	proto.RegisterType((*FSD)(nil), "monitor.FSD")
	proto.RegisterType((*FSDStats)(nil), "monitor.FSDStats")
	proto.RegisterType((*TopTalkersStats)(nil), "monitor.TopTalkersStats")
	proto.RegisterType((*Listeners)(nil), "monitor.Listeners")
	proto.RegisterType((*NetStats)(nil), "monitor.NetStats")
	proto.RegisterMapType((map[string]float64)(nil), "monitor.NetStats.StatesEntry")
	proto.RegisterType((*Statistic)(nil), "monitor.Statistic")
	proto.RegisterType((*Request)(nil), "monitor.Request")
}

func init() {
	proto.RegisterFile("api/MonitorService.proto", fileDescriptor_2301b6814c8530ba)
}

var fileDescriptor_2301b6814c8530ba = []byte{
	// 683 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0x9c, 0x34, 0x3f, 0xbe, 0xe9, 0xf7, 0xb5, 0x9d, 0xaf, 0x42, 0x56, 0x25, 0xa4, 0xca,
	0x2c, 0x28, 0x5d, 0xb8, 0x28, 0x55, 0x25, 0x0a, 0x2b, 0x20, 0x54, 0x14, 0x4a, 0x17, 0xe3, 0xae,
	0x90, 0x50, 0xe4, 0xd8, 0xe3, 0x6a, 0x14, 0xd7, 0x33, 0x9d, 0x19, 0x07, 0xe5, 0x21, 0x78, 0x00,
	0x9e, 0x83, 0x17, 0x44, 0xf3, 0x67, 0x87, 0xd2, 0x4d, 0x74, 0xef, 0x9d, 0xe3, 0xe3, 0x7b, 0x8e,
	0xcf, 0x04, 0xa2, 0x8c, 0xd3, 0x93, 0x2f, 0xac, 0xa6, 0x8a, 0x89, 0x94, 0x88, 0x15, 0xcd, 0x49,
	0xc2, 0x05, 0x53, 0x0c, 0x8d, 0xee, 0xec, 0x34, 0xfe, 0x04, 0xf0, 0x76, 0x75, 0x9b, 0xae, 0xe5,
	0x15, 0xcb, 0x0a, 0xb4, 0x0b, 0x7d, 0x56, 0x93, 0x28, 0x38, 0x0c, 0x8e, 0x02, 0xac, 0x4b, 0x84,
	0x60, 0xab, 0xa4, 0x2b, 0x12, 0xf5, 0xcc, 0xc8, 0xd4, 0xe8, 0x09, 0x0c, 0xef, 0x9b, 0x4c, 0x11,
	0x11, 0xf5, 0xcd, 0xd4, 0x75, 0xf1, 0xcc, 0x70, 0xbd, 0xe7, 0x8d, 0xe7, 0x6a, 0xa4, 0xf0, 0x5c,
	0x8d, 0x14, 0x7a, 0x22, 0xd7, 0xd2, 0x51, 0xe9, 0x52, 0xb3, 0xd3, 0xa2, 0x22, 0x8e, 0xc7, 0xd4,
	0xf1, 0x47, 0x18, 0xcf, 0xa8, 0x5c, 0x5e, 0xd6, 0x25, 0xd3, 0x4f, 0x28, 0x2e, 0x3d, 0x87, 0xe2,
	0x12, 0xed, 0xc3, 0x60, 0xb9, 0x10, 0xdc, 0xb3, 0xd8, 0xc6, 0x4e, 0xbf, 0x73, 0xe9, 0x88, 0x6c,
	0x13, 0xff, 0x08, 0x20, 0xd4, 0x54, 0xa9, 0xca, 0x94, 0x44, 0xa7, 0x30, 0x90, 0xba, 0x88, 0x82,
	0xc3, 0xfe, 0xd1, 0x64, 0xfa, 0x34, 0x71, 0x16, 0x24, 0x2d, 0x24, 0x31, 0xbf, 0x1f, 0x6a, 0x25,
	0xd6, 0xd8, 0x62, 0x0f, 0x3e, 0x03, 0x74, 0x43, 0xbd, 0xce, 0x92, 0xac, 0xcd, 0x3a, 0x21, 0xd6,
	0x25, 0x7a, 0x0e, 0x83, 0x55, 0x56, 0x35, 0xd6, 0x9f, 0xc9, 0x74, 0xef, 0x0f, 0x52, 0x2d, 0x01,
	0xdb, 0xf3, 0xd7, 0xbd, 0x57, 0x41, 0x7c, 0x0f, 0xfd, 0x8b, 0x74, 0xa6, 0xed, 0x93, 0xac, 0x11,
	0x39, 0x71, 0x44, 0xae, 0x43, 0xff, 0x41, 0xaf, 0xb4, 0xba, 0x42, 0xdc, 0x2b, 0x8d, 0x28, 0xc5,
	0x54, 0x56, 0x79, 0x51, 0xa6, 0xd1, 0x96, 0x35, 0x92, 0x14, 0xd1, 0x96, 0xb5, 0x4c, 0xd7, 0x28,
	0x82, 0x11, 0x27, 0x22, 0x27, 0xb5, 0x8a, 0x06, 0x66, 0xec, 0xdb, 0x78, 0x01, 0xe3, 0x8b, 0x74,
	0x66, 0x0d, 0x38, 0x86, 0xb0, 0x94, 0xc5, 0xa2, 0x62, 0xf9, 0xd2, 0x9b, 0xb0, 0xdd, 0xee, 0x7b,
	0x91, 0xce, 0x70, 0x77, 0xec, 0xb0, 0xb4, 0x66, 0x05, 0xd1, 0x2b, 0x3d, 0x8e, 0xb5, 0xc7, 0xf1,
	0x1e, 0xec, 0xdc, 0x30, 0x7e, 0x93, 0x55, 0x4b, 0x22, 0xa4, 0x79, 0x55, 0xfc, 0x0d, 0xc2, 0x2b,
	0x2a, 0x15, 0xa9, 0x89, 0x90, 0xda, 0x35, 0x4e, 0x0b, 0xef, 0x1a, 0xa7, 0x85, 0xd3, 0x20, 0x9c,
	0x56, 0x53, 0x6b, 0x57, 0x4c, 0x34, 0x73, 0x23, 0x37, 0xc4, 0xae, 0xd3, 0x58, 0xce, 0x84, 0x32,
	0x7a, 0x07, 0xd8, 0xd4, 0xf1, 0xaf, 0x00, 0xc6, 0xd7, 0x44, 0x59, 0x59, 0x67, 0xb0, 0xad, 0x9a,
	0x79, 0xe5, 0x5f, 0xe7, 0x94, 0xa1, 0x76, 0xdb, 0x76, 0x11, 0x3c, 0x51, 0x4d, 0xb7, 0xd5, 0x19,
	0x0c, 0xf5, 0x27, 0x6e, 0xe5, 0x75, 0x79, 0xf0, 0xcc, 0x26, 0x0e, 0xc4, 0xe5, 0xc1, 0x81, 0x0f,
	0xce, 0x61, 0xb2, 0x31, 0x7e, 0x24, 0x11, 0xfb, 0x9b, 0x89, 0x08, 0x36, 0x3f, 0xff, 0xcf, 0x1e,
	0x84, 0xfa, 0x59, 0x2a, 0x15, 0xcd, 0x51, 0x02, 0x63, 0xb9, 0x96, 0xf3, 0x8a, 0x65, 0xd6, 0x9a,
	0xc9, 0xf4, 0xff, 0x76, 0x83, 0xee, 0x46, 0xe2, 0x91, 0x74, 0x57, 0x33, 0x81, 0x71, 0xce, 0x1b,
	0x8b, 0xef, 0xfd, 0x8d, 0x77, 0xb7, 0x0e, 0x8f, 0x72, 0x77, 0xfd, 0x4e, 0x20, 0x2c, 0xa8, 0x5c,
	0xce, 0x69, 0x5d, 0x32, 0x63, 0xe9, 0xa6, 0x27, 0x6d, 0xe4, 0xf1, 0xb8, 0xf0, 0x77, 0xed, 0x18,
	0x46, 0xa5, 0xb4, 0xf0, 0xad, 0x07, 0x61, 0xf6, 0x11, 0xc2, 0xc3, 0x52, 0x3a, 0x6c, 0x5f, 0x29,
	0x69, 0xc2, 0x36, 0x99, 0x46, 0x2d, 0xee, 0x41, 0x0c, 0xb0, 0x06, 0xa1, 0x67, 0xd0, 0xaf, 0x89,
	0x8a, 0x86, 0x0f, 0x38, 0xbd, 0xcb, 0x58, 0x9f, 0xc6, 0xd7, 0x30, 0xc2, 0xe4, 0xbe, 0x21, 0x52,
	0xe9, 0x30, 0x2b, 0x7a, 0x47, 0x58, 0xa3, 0x8c, 0x2f, 0x03, 0xec, 0x5b, 0xf4, 0x02, 0x76, 0xb3,
	0x15, 0x11, 0xd9, 0x2d, 0x99, 0xd3, 0x5a, 0x11, 0xb1, 0xca, 0x2a, 0x63, 0xc5, 0x00, 0xef, 0xb8,
	0xf9, 0xa5, 0x1b, 0x4f, 0x67, 0x30, 0x72, 0xff, 0x7b, 0xe8, 0x1c, 0xfe, 0x4d, 0x49, 0x5d, 0x74,
	0xce, 0xef, 0xb6, 0x3b, 0xb8, 0x57, 0x1e, 0x74, 0xc6, 0xb4, 0xa8, 0xf8, 0x9f, 0x97, 0xc1, 0xbb,
	0xc9, 0xd7, 0x30, 0x39, 0x79, 0x23, 0x78, 0x9e, 0x71, 0xba, 0xb0, 0x81, 0x3c, 0xfd, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0xc7, 0xf7, 0xaa, 0x9f, 0x55, 0x05, 0x00, 0x00,
}
